const ADMIN_ACTIONS = {
  GET_USERS: "GET_USERS",
  CHANGE_USER_STATUS: "CHANGE_USER_STATUS",
  APPROVE_ORGANIZER: "APPROVE_ORGANIZER",
  REJECT_ORGANIZER: "REJECT_ORGANIZER",
  OVERRIDE_EVENT: "OVERRIDE_EVENT",
  VIEW_ANALYTICS: "VIEW_ANALYTICS",
};

const ADMIN_ACTIONS_LIST = Object.values(ADMIN_ACTIONS);

module.exports = {
    ADMIN_ACTIONS,
    ADMIN_ACTIONS_LIST
};